#!/bin/bash

image="yuroyoro/ruby-build:1.0.0"

init() {
    repo="https://github.com/ruby/ruby.git"
    if [ -e "$1" ] ; then
        repo="$1"
    fi

    git clone $repo &&
    mkdir -p build &&
    mkdir -p install &&
    docker build --no-cache --tag=yuroyoro/ruby-build:1.0.0 .
}
docker_run() {
    # echo "docker run --rm -it -v $(pwd):/workdir $image $*"
    docker run --rm -it --privileged -v $(pwd):/workdir $image $*
}

docker_run_in_build() {
    docker run --rm -it --privileged -v $(pwd):/workdir -w /workdir/build $image $*
}

run_make() {
    docker_run_in_build make $*
}

cmd=$1
shift
case "$cmd" in
    init)
        git clone https://github.com/ruby/ruby.git &&
        mkdir -p build &&
        mkdir -p install &&
        docker build --no-cache --tag=yuroyoro/ruby-build:1.0.0 .
        ;;
    configure)
        docker_run_in_build ../ruby/configure --prefix=/workdir/install --enable-shared
        ;;
    make)
        run_make $*
        ;;
    build)
        run_make -j && run_make install-nodoc
        ;;
    clean)
        docker_run_in_build make clean
        ;;
    bash)
        docker_run bash
        ;;
    ruby)
        docker_run ./build/ruby $*
        ;;
    miniruby)
        docker_run ./build/miniruby $*
        ;;
    run)
        run_make run
        ;;
    irb)
        docker_run ./install/bin/irb $*
        ;;
    *)
        read -d '' help <<-EOF
Usage: $0 command

  init      Setup build image and check out ruby source
  configure configure
  make      run make command in docker
  build     make -j && make clean
  clean     make clean
  ruby      run compiled ruby
  miniruby  run compiled miniruby
  run       run ruby/test.rb
  irb       launch irb
EOF
        echo "$help"
        exit 2
        ;;
esac
